### ISSUE TITLE
How to run example by execute_cora.py ?

### ISSUE THREAD

**Issue by Leonardo711** [PetarV-/GAT#10]
I've tried to run "python  execute_cora.py", and it throws an error: " 

Traceback (most recent call last):
  File "execute_cora.py", line 70, in <module>
    residual=residual, activation=nonlinearity)
TypeError: unbound method inference() must be called with GAT instance as first argument (got Tensor instance instead)
" 
after tried to change line 22 : model = GAT(), it throws another error:
Traceback (most recent call last):
  File "execute_cora.py", line 70, in <module>
    residual=residual, activation=nonlinearity)
TypeError: inference() got multiple values for keyword argument 'bias_mat'

**Comment by Leonardo711** [comment]
I saw another issue #2
