### ISSUE TITLE
Code fails with tensorflow-2.9.1: module 'tensorflow' has no attribute 'layers'

### ISSUE THREAD

**Issue by yurivict** [PetarV-/GAT#87]
```
Traceback (most recent call last):
  File "/usr/home/yuri/nn-function-optimizer/GNN/GAT/execute_cora.py", line 5, in <module>
    from models import GAT
  File "/usr/home/yuri/nn-function-optimizer/GNN/GAT/models/__init__.py", line 1, in <module>
    from .gat import GAT
  File "/usr/home/yuri/nn-function-optimizer/GNN/GAT/models/gat.py", line 4, in <module>
    from utils import layers
  File "/usr/home/yuri/nn-function-optimizer/GNN/GAT/utils/layers.py", line 4, in <module>
    conv1d = tf.layers.conv1d
AttributeError: module 'tensorflow' has no attribute 'layers'
```

TensorFlow 2.9.2  was released in May 2022.

**Comment by PetarV-** [comment]
Hi Yuri,

Thanks for your issue!

For this specific repository, the emphasis is on providing the code in as-close-as-possible state to the one that produced the results in the GAT paper. 
As a result, we do not plan on upgrading the codebase to newer versions of TensorFlow.

Further, we make it clear in the `README` file:
* Which dependencies and TF versions were used when the code was last executed by us; and
* Explicit pointers to other libraries (more actively maintained) that support a GAT layer out-of-the-box; those libraries are recommended for downstream use.

I hope this answer is helpful!

Thanks,
Petar
